# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 210246b3ac1918b0eea06f0574dcb739be108d9a25481a19f011fddc68151848a7d4ebc363bd1df590803876a69d00008ed2373b7b7e9a79c44c37ffc5cadaa3

test:
  secret_key_base: dce820065620a3cc0f4087e6cd9a9b005db8940df6d4448d2e2f55682e777a3521f6a09b198e67c4d8748f984b008e0bb11f99a0b85b812943bf9c55236e726f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
